const careerOptionsData = [
  // ─── LEVEL 0: TOP-LEVEL ACADEMIC STAGES ───
  {
    _id: "after-10th",
    parent_id: null,
    title: "After 10th Grade",
    short_description: "Streams, polytechnic diploma, ITI, defence and foundational career choices.",
    summary: "Students completing 10th grade can choose academic streams (Science, Commerce, Arts), 3-year technical polytechnic diplomas, ITI vocational certifications, or defence foundation tracks.",
    duration: "1 to 6 years depending on pathway",
    cost: "Low to Moderate (Scholarships widely available)",
    difficulty: "Moderate",
    scope: "Foundation stage unlocking 500+ undergraduate, vocational, and technical career routes.",
    eligibility: ["Completed 10th Grade / Secondary School Examination", "Minimum 50-60% for competitive streams"],
    skills: ["Decision Making", "Core Mathematics & Science", "Language & Communication", "Logical Reasoning"],
    opportunities: ["Higher Secondary (11th & 12th)", "Polytechnic Engineering", "ITI Certifications", "Defence Training"],
    display_order: 1
  },
  {
    _id: "after-12th",
    parent_id: null,
    title: "After 12th Grade",
    short_description: "Undergraduate degree programs, engineering, medical, commerce, law and creative arts.",
    summary: "After completing Higher Secondary (12th Grade), students can enroll in undergraduate bachelor degree programs, professional entrance examinations (JEE, NEET, CLAT, CUET, CA Foundation), or specialized career diplomas.",
    duration: "3 to 5.5 years",
    cost: "Moderate to High",
    difficulty: "Moderate to High",
    scope: "Gateway to specialized professional careers, corporate recruitment, civil services, and postgraduate study.",
    eligibility: ["12th Grade Pass in relevant stream (Science / Commerce / Arts)", "Entrance exams as required"],
    skills: ["Subject Specialization", "Analytical Thinking", "Project Work", "Research & Application"],
    opportunities: ["Bachelor's Degree", "Professional Certifications", "Direct Campus Placement", "Study Abroad"],
    display_order: 2
  },
  {
    _id: "after-diploma",
    parent_id: null,
    title: "After Diploma",
    short_description: "Lateral entry B.Tech/BE degrees, junior engineer roles, PSU recruitment and specialist certifications.",
    summary: "Polytechnic diploma graduates can directly enter the 2nd year of 4-year engineering degrees (Lateral Entry B.Tech) or immediately step into Junior Engineer and Technical Officer positions.",
    duration: "2 to 3 years",
    cost: "Low to Moderate",
    difficulty: "Moderate",
    scope: "Practical hands-on technical background with accelerated path to engineering degrees or early industrial employment.",
    eligibility: ["3-Year Polytechnic Diploma with minimum 60% aggregate"],
    skills: ["Hands-on Technical Troubleshooting", "CAD / Tooling / Scripting", "Applied Electronics/Mechanicals", "Project Management"],
    opportunities: ["Lateral Entry B.Tech (2nd Year)", "Junior Engineer (JE) in PSUs / Railways", "Industrial Automation Specialist", "Entrepreneurial Contracting"],
    display_order: 3
  },
  {
    _id: "after-graduation",
    parent_id: null,
    title: "After Graduation",
    short_description: "Master's degrees, MBA, Civil Services (UPSC), tech corporate jobs, and research/PhD.",
    summary: "Graduates holding a Bachelor's degree can advance to leadership through MBA, M.Tech/MS, crack prestigious government exams (UPSC/SSC/Banking), or scale to senior engineering and consulting roles.",
    duration: "1 to 4 years",
    cost: "Moderate to High",
    difficulty: "High",
    scope: "Leadership, managerial, research, and high-impact specialized global careers.",
    eligibility: ["Bachelor's Degree in any discipline with minimum qualifying marks"],
    skills: ["Leadership & Strategy", "Domain Expertise", "Advanced Problem Solving", "System Architecture & Research"],
    opportunities: ["MBA / Master's Programs", "UPSC Civil Services / State PSC", "Senior Tech Leadership", "Doctoral Research (PhD)"],
    display_order: 4
  },

  // ─── LEVEL 1: AFTER 10TH BRANCHES ───
  {
    _id: "science-stream",
    parent_id: "after-10th",
    title: "Science Stream (PCM / PCB)",
    short_description: "Physics, Chemistry, Maths, and Biology foundation for engineering, medicine, and research.",
    summary: "The Science stream equips students with analytical and scientific principles, leading directly to careers in Engineering (PCM), Medicine & Healthcare (PCB), Biotechnology, Pure Sciences, and Aviation.",
    duration: "2 years (11th & 12th)",
    cost: "Moderate",
    difficulty: "Challenging",
    scope: "Widest career flexibility; enables entrance to all technical, medical, and scientific fields.",
    eligibility: ["Passed 10th with minimum 60% in Science & Mathematics"],
    skills: ["Calculus & Trigonometry", "Physics Problem Solving", "Organic & Inorganic Chemistry", "Scientific Experimentation"],
    opportunities: ["Engineering (JEE)", "Medical (NEET)", "Defense (NDA)", "Pure Research (IISER/NISER)"],
    display_order: 1
  },
  {
    _id: "commerce-stream",
    parent_id: "after-10th",
    title: "Commerce Stream",
    short_description: "Accounting, Economics, Business Studies and Mathematics for finance and management.",
    summary: "Focuses on commercial trade, financial accounting, economic theory, business administration, and taxation systems. Opens doors to CA, CS, Investment Banking, Fintech, and Corporate Law.",
    duration: "2 years (11th & 12th)",
    cost: "Low to Moderate",
    difficulty: "Moderate",
    scope: "Thriving corporate and startup demand across accounting, audit, financial analysis, and business consulting.",
    eligibility: ["Passed 10th Grade"],
    skills: ["Financial Accounting", "Spreadsheet Modelling", "Economic Analysis", "Business Law Fundamentals"],
    opportunities: ["Chartered Accountancy (CA)", "B.Com / BBA / BMS", "Company Secretary (CS)", "Banking & Stock Markets"],
    display_order: 2
  },
  {
    _id: "arts-stream",
    parent_id: "after-10th",
    title: "Arts & Humanities Stream",
    short_description: "History, Political Science, Psychology, Sociology, and Literature for civil services, law, and creative arts.",
    summary: "Broad curriculum exploring human behavior, political systems, literature, media, and legal structures. Excellent stepping stone for UPSC Civil Services, Corporate Law, Journalism, and UI/UX Design.",
    duration: "2 years (11th & 12th)",
    cost: "Low to Moderate",
    difficulty: "Moderate",
    scope: "High growth in media, legal consultancy, civil administration, creative design, and public policy.",
    eligibility: ["Passed 10th Grade"],
    skills: ["Critical Thinking", "Content Writing & Rhetoric", "Public Policy Analysis", "Visual & Cultural Literacy"],
    opportunities: ["Integrated Law (BA LLB)", "Journalism & Media", "Civil Services Preparation", "Design & Fine Arts"],
    display_order: 3
  },
  {
    _id: "polytechnic-diploma",
    parent_id: "after-10th",
    title: "Polytechnic Diploma (3 Years)",
    short_description: "Practical engineering training in Computer, Mechanical, Electrical, and Civil disciplines.",
    summary: "A 3-year technical diploma focusing on hands-on lab work, engineering fundamentals, and industrial training. Diploma holders are eligible for direct lateral entry to 2nd year B.Tech degrees.",
    duration: "3 years",
    cost: "Low to Moderate (Govt Polytechnics highly affordable)",
    difficulty: "Moderate",
    scope: "Immediate industrial employability as Junior Engineers plus pathway to degree engineering programs.",
    eligibility: ["10th Grade with Mathematics and Science"],
    skills: ["Applied Engineering Practices", "Circuit Design / CAD Modeling", "Workshop Skills", "Code & Diagnostics"],
    opportunities: ["Lateral Entry B.Tech", "Junior Engineer in PSUs & Railways", "Plant Maintenance Engineer"],
    display_order: 4
  },
  {
    _id: "iti-vocational",
    parent_id: "after-10th",
    title: "ITI & Skill Development",
    short_description: "Short-term trade certifications in Electrician, Fitter, CNC machining, and Automotive.",
    summary: "Industrial Training Institutes (ITIs) offer government-certified vocational skill training for rapid employment in manufacturing, construction, electronics, and technical contracting.",
    duration: "1 to 2 years",
    cost: "Very Low",
    difficulty: "Hands-on Practical",
    scope: "High domestic and international demand for certified skilled technicians and self-employed tradespeople.",
    eligibility: ["10th Grade Pass"],
    skills: ["Equipment Maintenance", "Wiring & Soldering", "Machining & Blueprint Reading", "Industrial Safety"],
    opportunities: ["Certified Industrial Electrician", "Railway Technician", "Private Workshop Contractor"],
    display_order: 5
  },

  // ─── LEVEL 1: AFTER 12TH BRANCHES ───
  {
    _id: "engineering-and-technology",
    parent_id: "after-12th",
    title: "Engineering & Technology (B.Tech / BE)",
    short_description: "Computer science, AI/ML, data science, electronics, robotics, and mechanical systems.",
    summary: "Premier 4-year technical undergraduate education combining rigorous mathematics, software development, hardware architecture, and cutting-edge industrial innovation.",
    duration: "4 years",
    cost: "Moderate to High",
    difficulty: "Challenging",
    scope: "Global demand across software engineering, artificial intelligence, semiconductor chips, and infrastructure.",
    eligibility: ["12th Grade with Physics, Chemistry, Mathematics (PCM)", "Qualifying score in JEE / State CET"],
    skills: ["Software Engineering & Algorithms", "System Architecture", "Mathematics & Statistics", "Team Collaboration"],
    opportunities: ["Software Developer", "Data Scientist", "Cloud Architect", "Robotics Engineer"],
    display_order: 1
  },
  {
    _id: "medical-and-healthcare",
    parent_id: "after-12th",
    title: "Medical & Healthcare (MBBS / BDS / Allied)",
    short_description: "Clinical medicine, dentistry, pharmacy, biotechnology, and healthcare management.",
    summary: "Clinical, biomedical, and pharmaceutical education dedicated to human health, patient diagnosis, surgery, pharmacology, and medical research.",
    duration: "4.5 to 5.5 years (including internship)",
    cost: "Moderate to High",
    difficulty: "Very High / Competitive",
    scope: "Lifelong noble career with worldwide clinical demand, private practice opportunities, and specialized medical research.",
    eligibility: ["12th Grade with Physics, Chemistry, Biology (PCB)", "NEET Examination"],
    skills: ["Clinical Diagnosis & Patient Care", "Biochemistry & Pathology", "Pharmacology", "Surgical Basics"],
    opportunities: ["Medical Doctor (MBBS)", "Dental Surgeon (BDS)", "Biomedical Researcher", "Hospital Administrator"],
    display_order: 2
  },
  {
    _id: "commerce-finance-undergrad",
    parent_id: "after-12th",
    title: "Commerce, Finance & Banking (B.Com / BBA)",
    short_description: "Corporate finance, investment banking, taxation, fintech, and business analytics.",
    summary: "Undergraduate programs preparing professionals for equity research, corporate balance sheet auditing, venture capital, banking, and strategic commercial management.",
    duration: "3 to 4 years",
    cost: "Moderate",
    difficulty: "Moderate",
    scope: "Essential pillars of corporate operations, wealth management, startup funding, and global accounting firms.",
    eligibility: ["12th Grade Pass in Commerce or with Mathematics"],
    skills: ["Financial Statement Analysis", "Portfolio Management", "Tax Law & Auditing", "Corporate Strategy"],
    opportunities: ["Chartered Accountant (CA)", "Financial Analyst", "Risk Management Consultant", "Investment Banker"],
    display_order: 3
  },
  {
    _id: "law-and-humanities-undergrad",
    parent_id: "after-12th",
    title: "Law & Public Policy (BA LLB / BBA LLB)",
    short_description: "5-year integrated law degrees, corporate litigation, intellectual property, and cyber law.",
    summary: "Integrated five-year legal training combining liberal arts or management with constitutional law, corporate jurisprudence, arbitration, and cyber regulations.",
    duration: "5 years",
    cost: "Moderate to High",
    difficulty: "High",
    scope: "Prestigious career in corporate counsel, courtroom litigation, judiciary services, and international arbitration.",
    eligibility: ["12th Grade in any stream", "CLAT / AILET Entrance Exam"],
    skills: ["Legal Research & Drafting", "Courtroom Advocacy", "Contract Negotiation", "Constitutional Law"],
    opportunities: ["Corporate Legal Counsel", "Litigation Advocate", "Judicial Magistrate", "Policy Advisor"],
    display_order: 4
  },
  {
    _id: "design-and-creative-media",
    parent_id: "after-12th",
    title: "Design, UI/UX & Digital Media (B.Des)",
    short_description: "Product design, user experience (UX), visual communication, animation, and digital media.",
    summary: "Creative undergraduate programs focused on digital user interfaces, industrial product styling, branding, 3D animation, game design, and immersive AR/VR experiences.",
    duration: "4 years",
    cost: "Moderate to High",
    difficulty: "Moderate (Portfolio Based)",
    scope: "Rapidly expanding tech industry demand for product designers, creative directors, and game developers.",
    eligibility: ["12th Grade in any stream", "Design Aptitude Tests (UCEED, NID DAT)"],
    skills: ["Figma & Design Systems", "User Research & Prototyping", "Typography & Color Theory", "3D Animation"],
    opportunities: ["Lead Product / UI-UX Designer", "Motion Graphic Artist", "Creative Director", "AR/VR Experience Creator"],
    display_order: 5
  },

  // ─── LEVEL 2: ENGINEERING DISCIPLINES (UNDER ENGINEERING) ───
  {
    _id: "cse",
    parent_id: "engineering-and-technology",
    title: "Computer Science & Engineering (CSE)",
    short_description: "Algorithms, software engineering, databases, networking, and distributed systems.",
    summary: "The flagship engineering branch covering data structures, object-oriented design, web architecture, cloud platforms, database systems, and software engineering methodologies.",
    duration: "4 years",
    cost: "Moderate to High",
    difficulty: "Challenging",
    scope: "Highest volume of tech campus placements, remote international opportunities, and startup founding potential.",
    eligibility: ["12th PCM with competitive rank in JEE Main / State CET"],
    skills: ["Data Structures & Algorithms (C++, Java, Python)", "Full Stack Web Technologies", "Database Management Systems (SQL & NoSQL)", "Operating Systems & Cloud Architecture"],
    opportunities: ["Software Development Engineer (SDE)", "Full Stack Developer", "Cloud Engineer", "Solutions Architect"],
    display_order: 1
  },
  {
    _id: "ai-ml-engineering",
    parent_id: "cse",
    title: "AI & Machine Learning Engineering",
    short_description: "Deep learning, neural networks, computer vision, large language models, and NLP.",
    summary: "Specialized branch of computer science focused on training machine learning algorithms, fine-tuning neural networks, building automated agents, and deploying enterprise GenAI solutions.",
    duration: "4 years (B.Tech) or 2 years (M.Tech/MS)",
    cost: "Moderate to High",
    difficulty: "Very High",
    scope: "Fastest-growing tech sector with premium compensation across global AI labs, enterprise tech, and robotics.",
    eligibility: ["Strong foundation in Linear Algebra, Calculus, Probability, and Python programming"],
    skills: ["PyTorch / TensorFlow / JAX", "Large Language Models & Prompt Engineering", "Computer Vision & Transformers", "MLOps & GPU Model Serving"],
    opportunities: ["AI Engineer", "Machine Learning Researcher", "Computer Vision Specialist", "NLP Architect"],
    display_order: 1
  },
  {
    _id: "data-science",
    parent_id: "cse",
    title: "Data Science & Big Data Analytics",
    short_description: "Statistical modeling, predictive analytics, data pipelines, business intelligence, and visualization.",
    summary: "Integrates statistical inference, big data infrastructure (Hadoop, Spark), machine learning, and business data visualization to extract actionable intelligence from massive datasets.",
    duration: "4 years",
    cost: "Moderate to High",
    difficulty: "Challenging",
    scope: "Crucial for tech, finance, healthcare, e-commerce, and logistics decision-making.",
    eligibility: ["B.Tech CSE/IT/Maths/Statistics background with strong analytical acumen"],
    skills: ["Python, R, SQL", "Pandas, NumPy, Scikit-Learn", "Tableau / PowerBI Data Storytelling", "Distributed Data Pipelines (Spark, Kafka)"],
    opportunities: ["Data Scientist", "Lead Data Analyst", "Data Engineer", "Business Intelligence Manager"],
    display_order: 2
  },
  {
    _id: "cybersecurity",
    parent_id: "cse",
    title: "Cybersecurity & Ethical Hacking",
    short_description: "Network security, vulnerability assessment, penetration testing, cryptography, and defense.",
    summary: "Focuses on safeguarding enterprise systems, cloud infrastructure, and data against cyberattacks, malware, zero-day vulnerabilities, and unauthorized breaches.",
    duration: "4 years (or specialized certification pathways)",
    cost: "Moderate",
    difficulty: "Challenging",
    scope: "Zero unemployment rate globally with massive government, banking, and defence contractor demand.",
    eligibility: ["Background in Computer Science / IT / Networking fundamentals"],
    skills: ["Penetration Testing (Kali Linux, Burp Suite)", "Network Protocols & Firewalls", "SIEM & Threat Hunting", "Applied Cryptography"],
    opportunities: ["Ethical Hacker / Penetration Tester", "SOC Analyst", "Chief Information Security Officer (CISO)", "Security Consultant"],
    display_order: 3
  },
  {
    _id: "full-stack",
    parent_id: "cse",
    title: "Full Stack Web & Cloud Engineering",
    short_description: "Modern frontend frameworks, backend microservices, REST/GraphQL APIs, and cloud deployments.",
    summary: "Covers end-to-end web product development: crafting responsive frontend user interfaces (React, Next.js), engineering resilient backend servers (Node.js, Go, Python), and orchestrating cloud databases.",
    duration: "4 years (or 6-12 month intensive specialization)",
    cost: "Low to Moderate",
    difficulty: "Moderate to High",
    scope: "Universal demand across thousands of startups, tech unicorns, and digital enterprises.",
    eligibility: ["Programming basics and passionate interest in building web applications"],
    skills: ["React, Next.js, TypeScript, Tailwind CSS", "Node.js, Express, Go, REST & GraphQL APIs", "PostgreSQL, MongoDB, Redis", "Docker, CI/CD, Cloud Deployment (AWS / GCP)"],
    opportunities: ["Senior Full Stack Developer", "Frontend Architect", "Backend Systems Engineer", "Technical Product Lead"],
    display_order: 4
  },
  {
    _id: "cloud-devops",
    parent_id: "cse",
    title: "Cloud Architecture & DevOps Engineering",
    short_description: "Infrastructure as Code, Kubernetes, CI/CD pipelines, AWS/GCP architecture, and SRE.",
    summary: "Specializes in automating software deployments, architecting scalable multi-region cloud infrastructures, managing Kubernetes clusters, and ensuring 99.99% system reliability.",
    duration: "4 years (or professional cloud certifications)",
    cost: "Moderate",
    difficulty: "Challenging",
    scope: "High-paying roles bridging software engineering and infrastructure management.",
    eligibility: ["Operating systems, Linux administration, and networking basics"],
    skills: ["AWS / Google Cloud / Azure Architecture", "Kubernetes & Docker Containerization", "Terraform / Infrastructure as Code", "CI/CD Pipelines (GitHub Actions, Jenkins)"],
    opportunities: ["DevOps Engineer", "Site Reliability Engineer (SRE)", "Cloud Solutions Architect", "Platform Engineer"],
    display_order: 5
  },
  {
    _id: "mobile-development",
    parent_id: "cse",
    title: "Mobile App Engineering (iOS & Android)",
    short_description: "Native iOS (Swift), Android (Kotlin), and cross-platform Flutter/React Native app development.",
    summary: "Specialized in creating high-performance consumer and enterprise mobile applications, responsive touch user interfaces, offline-first syncing, and mobile hardware integrations.",
    duration: "4 years (or specialized mobile track)",
    cost: "Moderate",
    difficulty: "Moderate",
    scope: "Massive consumer app ecosystem with millions of smartphone users worldwide.",
    eligibility: ["Object-oriented programming in Kotlin, Swift, or TypeScript"],
    skills: ["Flutter / React Native", "Kotlin & Android Jetpack Compose", "Swift & SwiftUI (iOS)", "Mobile APIs & Performance Profiling"],
    opportunities: ["Mobile Software Engineer", "iOS Developer", "Android Developer", "Lead Mobile Architect"],
    display_order: 6
  },

  // ─── MEDICAL SPECIFIC CAREERS ───
  {
    _id: "mbbs-doctor",
    parent_id: "medical-and-healthcare",
    title: "MBBS Doctor & Medical Specialist",
    short_description: "5.5-year medicine & surgery degree leading to MD/MS specialization in Cardiology, Neurology, Surgery.",
    summary: "Comprehensive medical training in anatomy, physiology, pharmacology, and clinical rotations, followed by residency and super-specialization.",
    duration: "5.5 years (including 1-year internship)",
    cost: "Moderate (Govt) to High (Private)",
    difficulty: "Extremely Competitive",
    scope: "Pinnacle of healthcare with eternal societal respect, clinical leadership, and global recognition.",
    eligibility: ["12th Grade PCB with top percentile in NEET-UG"],
    skills: ["Clinical Diagnosis", "Patient Care & Empathy", "Emergency Life Support", "Medical Pharmacology"],
    opportunities: ["Physician / Surgeon", "Hospital Consultant", "Chief Medical Officer", "Medical Researcher"],
    display_order: 1
  },
  {
    _id: "biotech-pharma",
    parent_id: "medical-and-healthcare",
    title: "Biotechnology & Pharmaceuticals",
    short_description: "Drug discovery, genetic engineering, molecular biology, and vaccine development.",
    summary: "Applies biological principles, bioinformatics, and genetic technology to synthesize life-saving therapies, vaccines, and advanced agricultural solutions.",
    duration: "4 years (B.Tech / B.Sc Biotechnology)",
    cost: "Moderate",
    difficulty: "Challenging",
    scope: "High growth in biopharma, genomics, and clinical trial research institutes worldwide.",
    eligibility: ["12th Grade with Biology and Chemistry"],
    skills: ["Molecular Biology & Cell Culture", "Bioinformatics & Sequence Analysis", "HPLC / Chromatography", "Clinical Trial Protocols"],
    opportunities: ["Biomedical Scientist", "Drug Formulation Specialist", "Bioinformatics Analyst", "Quality Control Lead"],
    display_order: 2
  },

  // ─── COMMERCE & CA SPECIFIC CAREERS ───
  {
    _id: "chartered-accountancy",
    parent_id: "commerce-finance-undergrad",
    title: "Chartered Accountancy (CA)",
    short_description: "Premier qualification in auditing, taxation, corporate financial accounting, and consulting.",
    summary: "Administered by the Institute of Chartered Accountants, this prestigious 3-tier program (Foundation, Intermediate, Final) includes 3 years of practical articleship training.",
    duration: "4 to 5 years (concurrent with degree)",
    cost: "Low (Self-study & coaching)",
    difficulty: "Very High",
    scope: "Statutory monopoly on company audits, CFO leadership roles, and independent public practice.",
    eligibility: ["12th Grade in any stream (Commerce preferred)"],
    skills: ["Financial Audit & Assurance", "Direct & Indirect Tax Planning (GST/IT)", "Corporate Law & Compliance", "Forensic Accounting"],
    opportunities: ["Partner in Audit Firm", "Chief Financial Officer (CFO)", "Tax Consultant", "Investment Banker"],
    display_order: 1
  },
  {
    _id: "investment-banking",
    parent_id: "commerce-finance-undergrad",
    title: "Investment Banking & Corporate Finance",
    short_description: "Mergers & acquisitions, equity valuation, initial public offerings (IPOs), and asset management.",
    summary: "Advises corporations and institutional investors on capital raising, multi-billion-dollar acquisitions, debt issuance, and strategic financial restructuring.",
    duration: "3 to 5 years (BBA/B.Com followed by CFA / MBA Finance)",
    cost: "Moderate to High",
    difficulty: "High",
    scope: "Top tier Wall Street and global financial institutions with very high compensation.",
    eligibility: ["B.Com / BBA / Economics with strong financial mathematics and modeling skills"],
    skills: ["Financial Modeling & DCF Valuation", "Mergers & Acquisitions (M&A)", "Bloomberg Terminal & Market Analytics", "Deal Pitching"],
    opportunities: ["Investment Banking Analyst", "Private Equity Associate", "Hedge Fund Trader", "Portfolio Manager"],
    display_order: 2
  },

  // ─── AFTER GRADUATION PATHS ───
  {
    _id: "mba-management",
    parent_id: "after-graduation",
    title: "Master of Business Administration (MBA)",
    short_description: "Top business school programs in Strategy, Marketing, Finance, Operations, and Consulting.",
    summary: "Two-year postgraduate leadership degree developing strategic vision, team leadership, corporate strategy, case study methodologies, and executive networking.",
    duration: "2 years",
    cost: "Moderate to High",
    difficulty: "Challenging (CAT / GMAT / XAT)",
    scope: "Fast-track vehicle to executive management, management consulting, and senior business leadership.",
    eligibility: ["Bachelor's degree in any field with qualifying CAT/GMAT score"],
    skills: ["Strategic Management", "Financial Decision Making", "Brand & Product Marketing", "Organizational Leadership"],
    opportunities: ["Management Consultant (McKinsey/BCG)", "Product Manager", "Chief Operating Officer", "Strategy Director"],
    display_order: 1
  },
  {
    _id: "civil-services-upsc",
    parent_id: "after-graduation",
    title: "Civil Services & Public Administration (UPSC)",
    short_description: "Indian Administrative Service (IAS), Police (IPS), Foreign Service (IFS), and Central Services.",
    summary: "The nation's most prestigious competitive exam recruiting district administrators, police leaders, diplomats, and senior policy makers across government ministries.",
    duration: "1 to 3 years dedicated preparation",
    cost: "Low to Moderate",
    difficulty: "Extremely Competitive",
    scope: "Direct authority over district governance, public policy formulation, and societal transformation.",
    eligibility: ["Graduate in any discipline aged 21-32 years"],
    skills: ["General Studies & Current Affairs", "Essay Writing & Articulation", "Administrative Ethics", "Critical Decision Making"],
    opportunities: ["District Magistrate / IAS Officer", "Superintendent of Police (IPS)", "Diplomat / Ambassador (IFS)", "Revenue Commissioner (IRS)"],
    display_order: 2
  }
];

module.exports = careerOptionsData;
