DELETE FROM roadmaps;
DELETE FROM career_options;

INSERT INTO career_options
(id, parent_id, title, short_description, summary, duration, cost, difficulty, scope, eligibility, skills, opportunities, display_order)
VALUES
('after-10th', NULL, 'After 10th', 'Streams, diploma, ITI, skills, jobs and business options.', 'Students after 10th can continue with academic streams or choose practical skill paths. The goal is to understand every option before selecting a route.', '1 to 6 years depending on path', 'Low to high', 'Varies by route', 'Foundation stage with many academic and skill opportunities', '["Passed class 10","Interest and aptitude discussion","Basic digital literacy"]', '["Decision making","Subject awareness","Communication","Self learning"]', '["Higher studies","Early earning","Government jobs","Skill careers","Business"]', 1),
('after-12th', NULL, 'After 12th', 'Degree, professional courses, entrance exams and jobs.', 'After 12th, students can enter degree programs, professional courses, government exams, skill programs or entrepreneurship.', '6 months to 5 years', 'Medium to high', 'Moderate to competitive', 'Specialization stage for career building', '["Passed class 12","Stream-specific eligibility may apply"]', '["Entrance preparation","Research","Portfolio building"]', '["Degrees","Professional careers","Competitive exams","Startups"]', 2),
('after-diploma', NULL, 'After Diploma', 'Job, lateral entry B.Tech, training and specialization.', 'Diploma students can start technical jobs or continue to engineering through lateral entry.', 'Immediate to 3 years', 'Low to medium', 'Practical and technical', 'Industry-ready technical route', '["Diploma completion","Branch skills"]', '["Technical practice","Problem solving","Workshop skills"]', '["Junior engineer","B.Tech lateral entry","Technician","Apprenticeship"]', 3),
('after-degree', NULL, 'After Graduation', 'Jobs, higher studies, civil services, research or business.', 'Graduates can enter professional jobs, postgraduate study, public service, research or entrepreneurship.', 'Immediate to 5 years', 'Low to high', 'Career defining', 'Professional entry stage', '["Degree completion","Portfolio or exam preparation"]', '["Interview readiness","Domain depth","Communication"]', '["Private jobs","M.Tech/MS/MBA","UPSC","Research","Startup"]', 4),

('science', 'after-10th', 'Science Stream', 'PCMB, PCMC, PCB, PCME and technology routes.', 'Science develops analytical ability through physics, chemistry, mathematics, biology and computers. It leads to engineering, medical, research, technology, aviation and defence officer routes.', '2 years for PU/Class 11-12', 'Medium; coaching may increase cost', 'High if JEE/NEET integrated', 'Engineering, medical, research, technology, aviation', '["Passed 10th","Interest in maths or science","Consistent study habit"]', '["Analytical thinking","Mathematics","Scientific reasoning","Coding basics"]', '["Engineering","Medical","Research","AI/Data Science","NDA"]', 1),
('commerce', 'after-10th', 'Commerce Stream', 'Accounts, economics, business and finance.', 'Commerce builds knowledge of business, accounts, finance, taxation, economics and entrepreneurship.', '2 years plus degree path', 'Low to medium', 'Moderate; professional exams are hard', 'CA, CS, B.Com, BBA, finance and business', '["Passed 10th","Interest in business and numbers"]', '["Accounting","Business awareness","Financial thinking","Data interpretation"]', '["CA","CS","BBA","Finance","Banking","Business"]', 2),
('arts', 'after-10th', 'Arts and Humanities', 'History, political science, psychology, sociology and geography.', 'Humanities develops understanding of society, governance, culture, human behavior and communication.', '2 years plus degree path', 'Low to medium', 'Moderate', 'UPSC, law, journalism, psychology and teaching', '["Passed 10th","Interest in reading and society"]', '["Writing","Critical thinking","Research","Public communication"]', '["Civil services","Law","Journalism","Psychology","Teaching"]', 3),
('diploma', 'after-10th', 'Diploma / Polytechnic', 'Engineering and applied diplomas after 10th.', 'Diploma is a practical technical route that can lead to jobs or B.Tech lateral entry.', '3 years', 'Medium', 'Practical technical learning', 'Mechanical, Civil, CSE, Electrical, ECE and specialized diplomas', '["Passed class 10","Entrance or merit depending on institute"]', '["Workshop practice","Technical basics","Applied problem solving"]', '["Junior engineer","Technician","B.Tech lateral entry"]', 4),
('iti', 'after-10th', 'ITI Industrial Training', 'Electrician, fitter, welder, mechanic and other trades.', 'ITI provides focused trade training for early employability in industry, construction, repair and services.', '1 to 2 years', 'Low', 'Hands-on skill intensive', 'Trade and technician jobs', '["Passed class 10 or sometimes 8th","Trade aptitude"]', '["Tool handling","Safety","Repair","Installation"]', '["Electrician","Fitter","Welder","Mechanic","Solar technician"]', 5),
('vocational', 'after-10th', 'Vocational / Skill Courses', 'Hospitality, design, media, beauty and wellness.', 'Vocational courses create practical employable skills for jobs, freelance work or small business.', '3 months to 2 years', 'Low to medium', 'Portfolio and practice focused', 'Freelance, job and small business', '["Interest in practical skill","Basic communication"]', '["Creative practice","Customer handling","Tools","Presentation"]', '["Hotel management","Graphic design","Animation","Photography","Makeup"]', 6),
('government-10', 'after-10th', 'Government Jobs after 10th', 'Railway Group D, SSC MTS, Post Office GDS and police.', 'Government routes after 10th provide early stable income but require exam preparation and patience.', '6 months to 2 years preparation', 'Low', 'Competitive', 'Stable income and public service', '["10th pass","Age criteria","Exam or physical standards"]', '["General knowledge","Reasoning","Aptitude","Fitness"]', '["Railway Group D","SSC MTS","Post Office GDS","Police Constable","Forest Guard"]', 7),
('digital', 'after-10th', 'Digital / Online Careers', 'Freelancing, coding, digital marketing, content and e-commerce.', 'Digital careers can start with self-learning, projects and online portfolio building.', '3 months to 4 years', 'Low to medium', 'Skill and portfolio dependent', 'Remote work, freelancing, tech jobs and startups', '["Internet access","Self-learning discipline","Project practice"]', '["Coding","Design","Marketing","Content creation","Analytics"]', '["Web development","Video editing","YouTube","E-commerce","Affiliate marketing"]', 8),
('business', 'after-10th', 'Business / Entrepreneurship', 'Family business, shop, trading, services and startups.', 'Business routes need market understanding, customer trust, money discipline and consistency.', 'Immediate start; long-term scaling', 'Low to high', 'Risk and execution heavy', 'Self-employment and startup growth', '["Business mindset","Basic money management"]', '["Sales","Finance","Operations","Customer service"]', '["Retail","Trading","Repair services","Food products","Startup"]', 9),

('engineering', 'science', 'Engineering and Technology', 'CSE, AI/Data Science, IT, Mechanical, Civil, Electrical and ECE.', 'Engineering is about building software, systems, machines, infrastructure and technical solutions.', '4 years after 12th; 3 years lateral after diploma', 'Medium to high', 'High; entrance and projects matter', 'Large job market in tech and core industries', '["12th Science with PCM or diploma lateral entry","Entrance exams may apply"]', '["Mathematics","Coding or core technical skill","Projects","Problem solving"]', '["Software developer","Engineer","Tech entrepreneur","PSU jobs","M.Tech/MS/MBA"]', 1),
('medical', 'science', 'Medical and Health Sciences', 'MBBS, BDS, BAMS, BHMS, nursing, pharmacy and allied health.', 'Medical careers focus on healthcare, treatment, patient care, diagnostics and medicines.', '3 to 6 years plus specialization', 'Medium to very high', 'Very competitive', 'Healthcare, hospitals, clinics, research and pharma', '["12th Science with Biology","NEET or course-specific admission"]', '["Biology","Empathy","Precision","Long-term discipline"]', '["Doctor","Dentist","Nurse","Physiotherapist","Pharmacist"]', 2),
('pure-science', 'science', 'Pure Science / Research', 'Physics, chemistry, mathematics and biology.', 'Pure science focuses on deep scientific understanding through B.Sc, M.Sc, PhD, teaching and research.', '3 to 8+ years', 'Low to medium', 'Conceptual and research intensive', 'Research, teaching, labs and scientific institutions', '["12th Science","Strong interest in one subject"]', '["Research thinking","Data analysis","Scientific writing"]', '["Scientist","Researcher","Professor","Lab roles"]', 3),
('aviation', 'science', 'Aviation and Aerospace', 'Commercial pilot, aerospace engineering and aircraft maintenance.', 'Aviation careers involve aircraft, flying, maintenance, air systems and aerospace technology.', '1 to 4 years', 'High for pilot training', 'Technical and medical requirements', 'Airlines, aerospace, maintenance and defence aviation', '["12th Science often required","Medical fitness for pilot roles"]', '["Physics","Precision","Safety mindset","Technical aptitude"]', '["Commercial Pilot","Aerospace Engineering","Aircraft Maintenance"]', 4),

('ca', 'commerce', 'Chartered Accountancy', 'Professional accounting, audit and taxation path.', 'CA is a respected commerce route focused on accounting, audit, taxation and finance.', '4 to 5 years average', 'Medium', 'Very difficult professional exam', 'Audit firms, companies, finance and independent practice', '["Commerce helpful but not mandatory","CA Foundation route"]', '["Accounting","Taxation","Discipline","Analysis"]', '["CA practice","Audit","Tax consultant","Finance manager"]', 1),
('bba-mba', 'commerce', 'BBA / MBA Management', 'Business administration and management route.', 'Management route prepares students for business leadership, marketing, HR, finance, operations and entrepreneurship.', '3 years BBA; 2 years MBA later', 'Medium to high', 'Moderate to competitive', 'Management, consulting, business analyst and startup roles', '["Any stream for many programs","Entrance for top institutes"]', '["Communication","Leadership","Data interpretation","Strategy"]', '["Manager","Consultant","Entrepreneur","Business analyst"]', 2),
('law', 'commerce', 'Law', 'CLAT, LLB, legal advisor and judiciary.', 'Law develops legal reasoning, argumentation, contracts, rights and governance knowledge.', '5-year integrated LLB or 3-year LLB after degree', 'Medium', 'Reading and reasoning intensive', 'Lawyer, judge, legal advisor and corporate law', '["12th for integrated law","Graduation for 3-year LLB"]', '["Reading","Writing","Argument","Research"]', '["Lawyer","Judge","Legal advisor","Corporate counsel"]', 3),

('civil-services', 'arts', 'Civil Services', 'UPSC, state PSC and public administration.', 'Civil services involve governance, administration, policy, public welfare and leadership.', 'Degree plus 1 to 3 years preparation', 'Low to medium', 'Very competitive', 'IAS, IPS, IFS, state services and administration', '["Graduation required for UPSC","Age and attempt criteria"]', '["Reading","Writing","Current affairs","Analysis"]', '["IAS","IPS","IFS","State PSC","Public administration"]', 1),
('journalism', 'arts', 'Journalism and Media', 'News, reporting, content, communication and digital media.', 'Journalism suits students who like writing, speaking, research and public communication.', '3 years degree or shorter diploma', 'Low to medium', 'Portfolio dependent', 'Media houses, digital news, content strategy and communication', '["12th pass","Strong communication interest"]', '["Writing","Research","Speaking","Editing"]', '["Reporter","Editor","Content writer","Media producer"]', 2),
('psychology', 'arts', 'Psychology', 'Human behavior, counselling, mental health and research.', 'Psychology studies behavior, emotions, learning and mental processes.', '3 years degree plus higher studies for clinical roles', 'Medium', 'Conceptual and practice based', 'Counselling, HR, education, mental health and research', '["12th pass","Higher study needed for licensed practice"]', '["Listening","Research","Empathy","Analysis"]', '["Counsellor","Psychologist","HR","Research assistant"]', 3),

('cse', 'engineering', 'Computer Science Engineering', 'Software, data, systems and programming.', 'CSE focuses on programming, algorithms, software systems, data, AI and computing careers.', '4 years', 'Medium to high', 'High project competition', 'Software jobs, AI, cybersecurity, startups and research', '["12th PCM or diploma lateral entry","Entrance may apply"]', '["Programming","DSA","Projects","Debugging"]', '["Software Developer","AI Engineer","Data Engineer","Cybersecurity Analyst"]', 1),
('ai-ds', 'engineering', 'AI and Data Science', 'Machine learning, analytics, automation and data.', 'AI/Data Science combines maths, programming and data to build intelligent systems.', '4 years or certifications after basics', 'Medium to high', 'Maths and coding intensive', 'AI, analytics, automation, health tech and finance tech', '["PCM helpful","Programming interest"]', '["Python","Statistics","Machine learning","Data visualization"]', '["AI Engineer","Data Scientist","ML Engineer","Analytics Consultant"]', 2),
('mechanical', 'engineering', 'Mechanical Engineering', 'Machines, manufacturing, design and core industry.', 'Mechanical focuses on machines, manufacturing, thermal systems, design and production.', '4 years', 'Medium', 'Technical core learning', 'Manufacturing, automobile, energy, design and operations', '["12th PCM or diploma lateral entry"]', '["CAD","Mechanics","Production","Problem solving"]', '["Design Engineer","Production Engineer","Maintenance Engineer"]', 3),
('mbbs', 'medical', 'MBBS Doctor', 'Doctor route through NEET and medical college.', 'MBBS is the main route to become a doctor and serve in hospitals, clinics and healthcare systems.', '5.5 years plus specialization', 'High to very high', 'Extremely competitive', 'Doctor, specialist, hospital, clinic and public health', '["12th PCB","NEET qualification"]', '["Biology","Patient care","Discipline","Decision making"]', '["Doctor","Specialist","Public health officer","Clinic owner"]', 1),
('nursing', 'medical', 'Nursing', 'Patient care, hospitals and healthcare services.', 'Nursing is a high-demand healthcare career focused on patient care and hospital systems.', '3 to 4 years', 'Medium', 'Practical and service focused', 'Hospitals, clinics, community health and abroad opportunities', '["12th Science preferred","Course-specific admission"]', '["Patient care","Communication","Medical basics","Responsibility"]', '["Staff Nurse","Community Nurse","Hospital supervisor"]', 2),

('data-science', 'ai-ds', 'Data Science Specialization', 'Data analysis, machine learning, statistics and business insights.', 'Data Science is a strong engineering-related route for students who like mathematics, programming, patterns and decision making from data.', '4 years B.Tech plus projects/internships; 6 to 12 months extra portfolio work', 'Medium to high', 'Maths, coding and project intensive', 'Analytics, AI products, finance, healthcare, e-commerce and research teams', '["After 10th choose Science","After 12th choose PCM","Prefer CSE, AI/Data Science, IT or related engineering branch"]', '["Python","Statistics","SQL","Machine learning","Data visualization","Problem solving"]', '["Data Scientist","Data Analyst","ML Engineer","Business Analyst","Research Engineer"]', 1),
('cybersecurity', 'cse', 'Cybersecurity Engineering', 'Ethical hacking, network security, cloud security and digital forensics.', 'Cybersecurity is for students interested in protecting apps, networks, data and organizations from attacks.', '4 years B.Tech plus certifications and labs', 'Medium to high', 'High; requires continuous practice', 'Banks, IT companies, government cyber cells, product security and cloud security', '["After 10th choose Science","After 12th choose PCM","Prefer CSE, IT, ECE or cybersecurity specialization"]', '["Networking","Linux","Python","Web security","Cryptography basics","Incident response"]', '["Security Analyst","Ethical Hacker","SOC Analyst","Cloud Security Engineer","Digital Forensics Analyst"]', 2),
('full-stack', 'cse', 'Full Stack Development', 'Frontend, backend, databases, APIs and deployment.', 'Full Stack Development is a practical software path for building complete web applications from user interface to server and database.', '4 years engineering route or 1 to 2 years focused project path', 'Low to medium if self-learning; medium to high through college', 'Project and debugging intensive', 'Startups, SaaS companies, freelancing, product engineering and entrepreneurship', '["After 10th choose Science for engineering route","After 12th choose PCM","CSE/IT is ideal but strong portfolio also matters"]', '["HTML","CSS","JavaScript","React","Node.js","SQL","REST APIs","Git","Deployment"]', '["Full Stack Developer","Frontend Developer","Backend Developer","Software Engineer","Freelance Web Developer"]', 3),
('cloud-devops', 'cse', 'Cloud and DevOps Engineering', 'Cloud platforms, deployment, automation and reliable systems.', 'Cloud and DevOps focuses on running applications reliably using servers, containers, CI/CD, monitoring and automation.', '4 years engineering plus cloud labs and certifications', 'Medium', 'Practical systems learning', 'Cloud companies, IT services, SaaS operations and platform teams', '["After 10th choose Science","After 12th choose PCM","CSE/IT/ECE routes are suitable"]', '["Linux","AWS or Azure","Docker","CI/CD","Scripting","Monitoring","Networking basics"]', '["Cloud Engineer","DevOps Engineer","Site Reliability Engineer","Platform Engineer"]', 4),
('mobile-development', 'cse', 'Mobile App Development', 'Android, iOS, Flutter, React Native and app publishing.', 'Mobile App Development is for students who want to build useful apps for phones, startups, businesses and consumers.', '4 years engineering route or 1 to 2 years focused portfolio path', 'Low to medium', 'UI, logic and testing focused', 'App companies, startups, freelancing and product engineering', '["After 10th choose Science for engineering route","After 12th choose PCM","CSE/IT helpful but portfolio matters strongly"]', '["Java or Kotlin","Swift or Flutter","APIs","UI design basics","Testing","App store publishing"]', '["Android Developer","iOS Developer","Flutter Developer","Mobile Software Engineer"]', 5),
('ai-ml-engineering', 'ai-ds', 'AI and Machine Learning Engineering', 'ML models, automation, NLP, computer vision and AI products.', 'AI/ML Engineering builds intelligent systems using data, models, software engineering and experimentation.', '4 years B.Tech plus strong projects and internships', 'Medium to high', 'Maths, coding and research intensive', 'AI startups, product companies, automation, healthcare AI and research labs', '["After 10th choose Science","After 12th choose PCM","Prefer CSE, AI/Data Science, IT or related engineering branch"]', '["Python","Linear algebra","Machine learning","Deep learning basics","Model deployment","Data handling"]', '["AI Engineer","ML Engineer","NLP Engineer","Computer Vision Engineer","Research Engineer"]', 6);
